In [ ]:
%%time
import os
from glob import glob
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns
import re
import nltk
import json
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import regularizers
from keras import models
from keras import layers
from tensorflow.keras.layers import LSTM,GRU
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.metrics import average_precision_score,roc_auc_score, roc_curve, precision_recall_curve
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from tensorflow.keras.preprocessing.text import Tokenizer
np.random.seed(42)

CPU times: user 1.26 ms, sys: 16 µs, total: 1.28 ms
Wall time: 1.29 ms


In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
stops = set(stopwords.words("english"))
def cleantext(string):
    text = string.lower().split()
    text = " ".join(text)
    text = re.sub(r"http(\S)+",' ',text)    
    text = re.sub(r"www(\S)+",' ',text)
    text = re.sub(r"&",' and ',text)  
    tx = text.replace('&amp',' ')
    text = re.sub(r"[^0-9a-zA-Z]+",' ',text)
    text = text.split()
    text = [w for w in text if not w in stops]
    text = " ".join(text)
    return text

In [ ]:
%%time
path = "/content/drive/My Drive/SharedTasksParticipation/SharedTask@Constraint@AAAI2021/"
train_filename= path + "Constraint_English_Train.xlsx"
val_filename = path + "Constraint_English_Val.xlsx"
test_filename = path + "Constraint_English_Test.xlsx"

train = pd.read_excel(train_filename)
val = pd.read_excel(val_filename)
test = pd.read_excel(test_filename)

CPU times: user 294 ms, sys: 1.54 ms, total: 296 ms
Wall time: 305 ms


In [ ]:
train['train_label']= train.label.replace({'real':0,'fake':1})
val['val_label']= val.label.replace({'real':0,'fake':1})

In [ ]:
train['cleaned'] = train['tweet'].map(lambda x: cleantext(x))
val['cleaned'] = val['tweet'].map(lambda x: cleantext(x))
test['cleaned'] = test['tweet'].map(lambda x: cleantext(x))

In [ ]:
total_data=pd.concat([train.cleaned, val.cleaned, test.cleaned], axis=0)

In [ ]:
train

id  ...                                            cleaned
0        1  ...  cdc currently reports 99031 deaths general dis...
1        2  ...  states reported 1121 deaths small rise last tu...
2        3  ...  politically correct woman almost uses pandemic...
3        4  ...  indiafightscorona 1524 covid testing laborator...
4        5  ...  populous states generate large case counts loo...
...    ...  ...                                                ...
6415  6416  ...  tiger tested positive covid 19 please stay awa...
6416  6417  ...  autopsies prove covid 19 blood clot pneumonia ...
6417  6418  ...  post claims covid 19 vaccine already developed...
6418  6419  ...      aamir khan donate 250 cr pm relief cares fund
6419  6420  ...  93 days since last case covid 19 acquired loca...

[6420 rows x 5 columns]

In [ ]:
val

id  ...                                            cleaned
0        1  ...  chinese converting islam realising muslim affe...
1        2  ...  11 13 people diamond princess cruise ship inti...
2        3  ...    covid 19 caused bacterium virus treated aspirin
3        4  ...  mike pence rnc speech praises donald trump cov...
4        5  ...  6 10 sky edconwaysky explains latest covid19 d...
...    ...  ...                                                ...
2135  2136  ...  donald trump wrongly claimed new zealand big s...
2136  2137  ...  current understanding covid19 spreads mostly p...
2137  2138  ...  nothing screams sat around fuck lockdown quite...
2138  2139  ...    birx says covid 19 outbreak control people move
2139  2140  ...  another 4422 new coronavirus cases confirmed u...

[2140 rows x 5 columns]

In [ ]:
test

id  ...                                            cleaned
0        1  ...  daily update published states reported 734k te...
1        2  ...                              alfalfa cure covid 19
2        3  ...  president trump asked would catch coronavirus ...
3        4  ...  states reported 630 deaths still seeing solid ...
4        5  ...  sixth time global health emergency declared in...
...    ...  ...                                                ...
2135  2136  ...  coronavirusupdates state wise details total co...
2136  2137  ...  tonight 12 midnight onwards disaster managemen...
2137  2138  ...  296 new cases covid19nigeria plateau 85 enugu ...
2138  2139  ...  rt cdcemergency dyk cdcgov one stop shop covid...
2139  2140  ...  half pregnant women recently admitted uk hospi...

[2140 rows x 3 columns]

In [ ]:
total_data

0       cdc currently reports 99031 deaths general dis...
1       states reported 1121 deaths small rise last tu...
2       politically correct woman almost uses pandemic...
3       indiafightscorona 1524 covid testing laborator...
4       populous states generate large case counts loo...
                              ...                        
2135    coronavirusupdates state wise details total co...
2136    tonight 12 midnight onwards disaster managemen...
2137    296 new cases covid19nigeria plateau 85 enugu ...
2138    rt cdcemergency dyk cdcgov one stop shop covid...
2139    half pregnant women recently admitted uk hospi...
Name: cleaned, Length: 10700, dtype: object

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

def text_encoding(texts, labels, padding_length):
  tokenizer = Tokenizer()
  
  # Tokenizer is fitted into the texts
  tokenizer.fit_on_texts(texts)

  # Encoding texts into integer sequences
  sequences = tokenizer.texts_to_sequences(texts)
  # Pad sequences
  corpus = keras.preprocessing.sequence.pad_sequences(sequences, value=0.0,
                                                      padding='post', maxlen= padding_length)

  return corpus, labels, tokenizer

##
#max_words = 20000 # Based on number of unique words in the dataset
padding_length = 100
corpus, labels, tokenizer = text_encoding(total_data, train.train_label, padding_length)

In [ ]:
train_data, train_labels = corpus, labels

In [ ]:
print(training_data, training_labels)

[[  69  215  203 ...    0    0    0]
 [  12   18 6790 ...    0    0    0]
 [4792 1770  373 ...    0    0    0]
 ...
 [ 216  104    1 ...    0    0    0]
 [2806  899 2685 ...    0    0    0]
 [1560   42   83 ...    0    0    0]] [0 0 1 ... 1 1 0]


In [ ]:
word_index = tokenizer.word_index
vocab_size = len(tokenizer.word_index) + 1
print("Vocabulary Size :", vocab_size)

Vocabulary Size : 18243


In [ ]:
!wget http://nlp.stanford.edu/data/glove.6B.zip
!unzip glove.6B.zip

--2020-12-10 10:47:25--  http://nlp.stanford.edu/data/glove.6B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://nlp.stanford.edu/data/glove.6B.zip [following]
--2020-12-10 10:47:25--  https://nlp.stanford.edu/data/glove.6B.zip
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip [following]
--2020-12-10 10:47:25--  http://downloads.cs.stanford.edu/nlp/data/glove.6B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 862182613 (822M) [application/zip]
Saving to: ‘glove.6B.zip.1’

glove

KeyboardInterrupt: ignored

In [ ]:
GLOVE_EMB = '/content/glove.6B.100d.txt'

embeddings_index = {}

f = open(GLOVE_EMB)
for line in f:
  values = line.split()
  word = value = values[0]
  coefs = np.asarray(values[1:], dtype='float32')
  embeddings_index[word] = coefs
f.close()

print('Found %s word vectors.' %len(embeddings_index))

Found 400000 word vectors.


In [ ]:
embedding_matrix = np.zeros((vocab_size, 100))
for word, i in word_index.items():
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector

In [ ]:
## Defining Callbacks
def define_callback():
  keras.backend.clear_session()
  accuracy_threshold = .9999

  class myCallback(keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if(logs.get('accuracy')>accuracy_threshold):
          print("\nReached %2.2f%% accuracy so we will stop trianing" % (accuracy_threshold*100))
          self.model.stop_training = True

  acc_callback = myCallback()

  return acc_callback

# Define Checkpoint
def define_checkpoint():
  filepath = "ModelOnOurData.h5"
  checkpoint = keras.callbacks.ModelCheckpoint(filepath, monitor='val_accuracy', verbose=2, save_best_only=True, save_weights_only=False, mode='max')
  return checkpoint

In [ ]:
from tensorflow.keras.layers import Conv1D, Bidirectional, LSTM, Dense, Input, Dropout
from tensorflow.keras.layers import SpatialDropout1D
from tensorflow.keras.optimizers import Adam

In [ ]:
# Create Model
def create_model(embedding_dim):
  keras.backend.clear_session()

  model = keras.models.Sequential([
      keras.layers.Embedding(vocab_size, embedding_dim, input_length = padding_length),
      #keras.layers.Conv1D(64, 5, activation='relu'),
      #keras.layers.MaxPooling1D(5),
      #keras.layers.Bidirectional(LSTM(32, dropout=0.4)),
      #keras.layers.Dense(64, activation='relu'),
      #keras.layers.Dropout(0.5),
      keras.layers.Dense(64, activation='relu'),
      keras.layers.Flatten(),
      keras.layers.Dense(2, activation = 'softmax')
  ])

  model.summary()
  return model


# Compile Model
def compile_model(model):
  model.compile(optimizer=Adam(learning_rate=0.0001),
                  loss='sparse_categorical_crossentropy',
                  metrics='accuracy')
  return model


In [ ]:
%%time
## Callbacks are really important 

def run_callback_list():
  acc_callback = define_callback()
  checkpoint = define_checkpoint()
  return [acc_callback, checkpoint] 

callback_list = run_callback_list()

def run_model():
    embedding_dim = 100
    model = create_model(embedding_dim)
    model = compile_model(model)
    return model

## Create, Compile and Visualize the model
cnn_lstm_model = run_model() ## 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 100, 100)          1824300   
_________________________________________________________________
dense (Dense)                (None, 100, 64)           6464      
_________________________________________________________________
flatten (Flatten)            (None, 6400)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 12802     
Total params: 1,843,566
Trainable params: 1,843,566
Non-trainable params: 0
_________________________________________________________________
CPU times: user 70.9 ms, sys: 2.21 ms, total: 73.1 ms
Wall time: 60.4 ms


In [ ]:
cnn_lstm_model.layers[0].set_weights([embedding_matrix])
cnn_lstm_model.layers[0].trainable = False

In [ ]:
cnn_lstm_model_history = cnn_lstm_model.fit(train_data,
                              train_labels,
                              epochs = 50,
                              batch_size = 64,
                              verbose = 1,
                              validation_split = 0.15,
                              callbacks = callback_list)

ValueError: ignored

In [ ]:
val_sequences = tokenizer.texts_to_sequences(val.cleaned)
print(val_sequences[0:10])
val_data = keras.preprocessing.sequence.pad_sequences(val_sequences, value=0.0,
                                                      padding='post', maxlen= padding_length)
val_labels = val['val_label']

print(val_data[:5], val_data.shape)
print(val_labels[:5], val_labels.shape)

[[234, 9592, 4338, 828, 424, 4, 73], [106, 239, 8, 5084, 3991, 1683, 1347, 41, 236, 9, 1116, 1126, 16, 40, 346, 12], [1, 2, 392, 2526, 29, 859, 5044], [2014, 2032, 7757, 4078, 10896, 178, 43, 1, 2, 3937, 2174, 1010, 2457, 68, 23, 3636], [55, 63, 968, 1053, 110, 5, 38, 67, 2639, 77, 4, 38], [24, 1515, 135, 66, 959, 374, 851, 236, 44, 1971, 44, 1799, 637, 311, 42, 298, 3796, 3877, 2468, 4320, 5694], [27, 7, 24, 449, 5, 575, 1375, 290, 13, 31, 445, 57, 502, 6074, 75, 66, 17, 339, 371, 204, 122, 12, 375, 1700, 416, 156, 132], [39, 5, 297, 10464, 4462, 2419, 260, 166, 111, 8, 3791], [70, 262, 6100, 1111, 5572, 257, 931, 2911, 18, 1588, 2084, 315, 107, 3914, 2809, 248, 75], [2497, 448, 2176, 2420, 35, 284, 301]]
[[  234  9592  4338   828   424     4    73     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0 

In [ ]:
cnn_lstm_model=load_model("/content/ModelOnOurData.h5")
val_ls, val_acc = cnn_lstm_model.evaluate(val_data, val_labels)
print(val_labels)
print(val_ls, val_acc)
pred = np.argmax(cnn_lstm_model.predict(val_data), axis=-1)
print(pred)
print_metrices(pred, val_labels)
#plot_confusion_matrix(confusion_matrix(val['label'],pred),target_names=['real','fake'], normalize = False, \
                      #title = 'Confusion matix of SVM on val data')


#svm_val_misclass_df = val_ori[pred!=val['label']]

67/67 [==============================] - 0s 2ms/step - loss: 0.2093 - accuracy: 0.5262
0       1
1       1
2       1
3       1
4       0
       ..
2135    1
2136    0
2137    1
2138    1
2139    0
Name: val_label, Length: 2140, dtype: int64
0.2093476951122284 0.5261682271957397
[1 0 1 ... 1 1 0]
[[1040   80]
 [  86  934]]
              precision    recall  f1-score   support

           0       0.92      0.93      0.93      1120
           1       0.92      0.92      0.92      1020

    accuracy                           0.92      2140
   macro avg       0.92      0.92      0.92      2140
weighted avg       0.92      0.92      0.92      2140

Accuracy :  0.922429906542056
Precison :  0.9224660331422289
Recall :  0.922429906542056
F1 :  0.9224407057208079


# Prediction on test set

In [ ]:
test_sequences = tokenizer.texts_to_sequences(test.cleaned)
print(test_sequences[0:10])
test_data = keras.preprocessing.sequence.pad_sequences(test_sequences, value=0.0,
                                                      padding='post', maxlen= padding_length)

[[48, 34, 97, 12, 18, 9, 8531, 6, 3, 9714, 10, 251, 223, 1386, 2716, 80, 86, 83, 298, 406], [134, 1, 2], [68, 43, 633, 164, 2397, 4, 309, 4], [12, 18, 10, 113, 1415, 1972, 156, 984, 79, 105, 1879, 3011, 311, 42, 1649, 1530, 316, 69, 1498, 1692, 1879, 127, 86, 30, 79, 105, 1191], [3631, 86, 328, 20, 437, 1532, 535, 20, 2547, 1918, 354, 141], [292, 7603, 3401, 1562, 32, 1, 2], [704, 1785, 493, 3711, 84, 1948, 251, 3711, 84, 12, 25, 251, 12, 25, 493, 1540, 10360, 23, 493, 5099, 251], [67, 1692, 351, 6, 156, 52, 693, 3735, 1706, 35, 2200, 539, 1208], [48, 34, 97, 310, 13, 81, 61, 9, 62, 18, 183, 83, 139, 11, 214, 180, 9, 23, 203, 12, 25, 9, 53], [576, 19, 37, 536, 2824, 2100, 1287, 17, 20, 295, 228, 2604, 945, 1287, 4115, 17, 13, 9167, 1405, 687, 236, 9, 855, 251, 4115, 13085, 926, 17, 2491, 261, 236]]


In [ ]:
pred= np.argmax(cnn_lstm_model.predict(test_data), axis=-1)

In [ ]:
jongu = pd.DataFrame(pred, columns=['ll'])

In [ ]:
jongu

ll
0      0
1      1
2      1
3      0
4      0
...   ..
2135   0
2136   0
2137   0
2138   0
2139   1

[2140 rows x 1 columns]

In [ ]:
test['label']= jongu.ll.replace({0:'real',1:'fake'})

In [ ]:
test.head(15)

id  ... label
0    1  ...  real
1    2  ...  fake
2    3  ...  fake
3    4  ...  real
4    5  ...  real
5    6  ...  real
6    7  ...  real
7    8  ...  real
8    9  ...  real
9   10  ...  real
10  11  ...  fake
11  12  ...  fake
12  13  ...  real
13  14  ...  fake
14  15  ...  fake

[15 rows x 4 columns]

In [ ]:
test[['id','label']]

In [ ]:
test['label'].value_counts()

real    1109
fake    1031
Name: label, dtype: int64

In [ ]:
with open('svm(94.62).txt', 'w') as f:
  f.write("id,label\n")
  for i in range(len(pred_test)):
    id = test['id'][i]
    v = pred_test[i]
    f.write("%d,%s\n"%(id, v))